name: monitoring-stack

x-common-conf: &common-conf
    pull_policy: if_not_present
    restart: unless-stopped
    networks:
      monitoring-stack:

networks:
  monitoring-stack:

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.45.6
    <<: *common-conf
    ports:
      - name: web
        published: 9090
        target: 9090
    volumes:
      - "./config/prometheus.yaml:/etc/prometheus/prometheus.yml:ro"
      - "./config/rules.yaml:/etc/prometheus/rules.yml:ro"
      - "/home/server/data/prometheus:/prometheus"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
 
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.27.0
    <<: *common-conf
    ports:
      - name: web
        published: 9093
        target: 9093
    volumes:
      - "./config/alertmanager.yaml:/alertmanager/alertmanager.yml:ro"
    depends_on:
      - prometheus
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9093/-/healthy || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    container_name: grafana 
    image: grafana/grafana-enterprise:10.2.8
    <<: *common-conf
    ports:
      - name: web
        published: 3001
        target: 3000
    volumes:
       - "./config/grafana/provisioning/:/etc/grafana/provisioning/"
       - "/home/server/data/grafana:/var/lib/grafana"
    depends_on:
      - prometheus
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
  
  otel:
    container_name: otel
    image: otel/opentelemetry-collector-contrib:0.104.0
    <<: *common-conf
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - "./config/otel.yaml:/etc/otel-collector-config.yaml:ro"
      - "/:/hostfs:ro"
    ports:
      - name: health-check
        published: 13133
        target: 13133
      - name: grpc-receiver
        published: 4317
        target: 4317
      - name: prom-metrics
        published: 8888
        target: 8888
      - name: prom-exporter
        published: 8889
        target: 8889
      - name: zpages
        published: 55679
        target: 55679
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:13133/healthy"]
    #   interval: 20s
    #   timeout: 10s
    #   retries: 5
