name: monitoring-stack

x-common-conf: &common-conf
  pull_policy: if_not_present
  restart: unless-stopped
  networks:
    monitoring-stack:

# x-logging: &logging
#   logging:
#     driver: loki
#     options:
#       loki-url: "http://localhost:3100/loki/api/v1/push"
#       loki-batch-size: 100
#       loki-retries: 3
#       loki-max-backoff: 1000ms
#       loki-timeout: 3s

networks:
  monitoring-stack:

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.45.6
    <<: *common-conf
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=180d
      - --storage.tsdb.retention.size=100GB
    ports:
      - name: web
        published: 9090
        target: 9090
    volumes:
      - "./config/prometheus.yaml:/etc/prometheus/prometheus.yml:ro"
      - "./config/rules.yaml:/etc/prometheus/rules.yml:ro"
      - "/home/server/data/prometheus:/prometheus"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
 
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.27.0
    <<: *common-conf
    ports:
      - name: web
        published: 9093
        target: 9093
    volumes:
      - "./config/alertmanager.yaml:/alertmanager/alertmanager.yml:ro"
    depends_on:
      - prometheus
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9093/-/healthy || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    container_name: grafana 
    image: grafana/grafana-enterprise:10.2.8
    <<: *common-conf
    ports:
      - name: web
        published: 3001
        target: 3000
    volumes:
       - "./config/grafana/provisioning/:/etc/grafana/provisioning/"
       - "/home/server/data/grafana:/var/lib/grafana"
    depends_on:
      - prometheus
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  loki:
    container_name: loki
    image: grafana/loki:main-08615bf
    <<: *common-conf
    command: 
      - --config.file=/etc/loki/retention-config.yaml
    ports:
      - name: receiver
        published: 3100
        target: 3100
    volumes:
      - "./config/loki/retention-config.yaml:/etc/loki/retention-config.yaml"
 
  otel:
    container_name: otel
    image: otel/opentelemetry-collector-contrib:0.104.0
    <<: *common-conf
    environment: 
      NODE_NAME: 'central'
      NODE_IP: '255.255.255.255'
      NODE_ACCESS: 'internal'
    command: 
      - --config=/etc/otel-collector-config.yaml
    ports:
      - name: health-check
        published: 13133
        target: 13133
      - name: grpc-receiver
        published: 4317
        target: 4317
      - name: prom-metrics
        published: 8888
        target: 8888
      - name: prom-exporter
        published: 8889
        target: 8889
      - name: zpages
        published: 55679
        target: 55679
    volumes:
      - "./config/otel.yaml:/etc/otel-collector-config.yaml:ro"
      - "/:/hostfs:ro"


