receivers:
  otlp:
    protocols:
      grpc:
      http:

  hostmetrics:
    root_path: /hostfs
    collection_interval: 60s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:
  
      
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  # otlphttp:
  #   endpoint: "0.0.0.0:3100/otlp/v1/logs"


processors:
  batch:
  resourcedetection/docker:
    detectors: [env]


service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch, resourcedetection/docker]
      exporters: [prometheus]
    # logs:
    #   receivers: [otlphttp]
    #   processors: [batch]
    #   exporters: [loki]

extensions:
  health_check:
  health_check/1:
    endpoint: "localhost:13133"
    path: "/healthy"