receivers:
  otlp:
    protocols:
      grpc:
      http:

  hostmetrics:
    root_path: /hostfs
    collection_interval: 60s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:
  
  # docker_stats:
  #   endpoint: unix:///var/run/docker.sock
  #   collection_interval: 20s
  #   timeout: 20s
  #   api_version: 1.25
  #   metrics:  
  #     container.cpu.usage.total: 
  #       enabled: true
  #     container.cpu.utilization:
  #       enabled: true
  #     container.memory.percent:
  #       enabled: true
  #     container.memory.usage.limit:
  #       enabled: true
  #     container.memory.usage.total:
  #       enabled: true
  #     container.cpu.usage.system:
  #       enabled: true
  #     container.cpu.limit:
  #       enabled: true
  #     container.cpu.usage.percpu:
  #       enabled: true
  #     container.network.io.usage.rx_bytes:
  #       enabled: true
  #     container.network.io.usage.rx_dropped:
  #       enabled: true
  #     container.network.io.usage.tx_bytes:
  #       enabled: true
  #     container.network.io.usage.tx_dropped:
  #       enabled: true
  #     container.restarts:
  #       enabled: true
  #     container.uptime:
  #       enabled: true


      
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  # otlphttp:
  #   endpoint: "0.0.0.0:3100/otlp/v1/logs"


processors:
  batch:


service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [prometheus]
    # logs:
    #   receivers: [otlphttp]
    #   processors: [batch]
    #   exporters: [loki]

extensions:
  health_check:
  health_check/1:
    endpoint: "localhost:13133"
    path: "/healthy"