receivers:
  otlp:
    protocols:
      grpc:
      http:

  hostmetrics:
    root_path: /hostfs
    collection_interval: 120s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:
  
      
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  # otlphttp:
  #   endpoint: "0.0.0.0:3100/otlp/v1/logs"


processors:
  batch:
  metricstransform:
    transforms:
      - include: ^system\.
        match_type: regexp
        action: update
        operations:
          - action: add_label
            new_label: node
            new_value: ${env:NODE_NAME}
          - action: add_label
            new_label: ip
            new_value: ${env:NODE_IP}
          - action: add_label
            new_label: access
            new_value: ${env:NODE_ACCESS}


service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [metricstransform, batch]
      exporters: [prometheus]
    # logs:
    #   receivers: [otlphttp]
    #   processors: [batch]
    #   exporters: [loki]

extensions:
  health_check:
  health_check/1:
    endpoint: "localhost:13133"
    path: "/healthy"