apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # orgId: 1
    url: http://prometheus:9090
    editable: false
  
  - name: Loki 
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
